# Generated by Django 4.2.1 on 2023-09-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_product_image_link", models.CharField(max_length=500)),
                ("first_product_name", models.CharField(max_length=100)),
                ("first_product_text", models.CharField(max_length=500)),
                ("first_product_description", models.CharField(max_length=500)),
                ("first_product_previous_price", models.FloatField()),
                ("first_product_current_price", models.FloatField()),
                ("first_product_link", models.CharField(max_length=500)),
                ("second_product_image_link", models.CharField(max_length=500)),
                ("second_product_name", models.CharField(max_length=100)),
                ("second_product_text", models.CharField(max_length=500)),
                ("second_product_description", models.CharField(max_length=500)),
                ("second_product_previous_price", models.FloatField()),
                ("second_product_current_price", models.FloatField()),
                ("second_product_link", models.CharField(max_length=500)),
                ("third_product_image_link", models.CharField(max_length=500)),
                ("third_product_name", models.CharField(max_length=100)),
                ("third_product_text", models.CharField(max_length=500)),
                ("third_product_description", models.CharField(max_length=500)),
                ("third_product_previous_price", models.FloatField()),
                ("third_product_current_price", models.FloatField()),
                ("third_product_link", models.CharField(max_length=500)),
            ],
        ),
    ]
