# Generated by Django 4.2.1 on 2023-09-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="first_product_link",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="product",
            name="second_product_link",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="product",
            name="third_product_link",
            field=models.CharField(max_length=5000),
        ),
    ]
