# Generated by Django 4.2.1 on 2023-09-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_product_first_product_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="second_product_current_price",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="second_product_description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="second_product_image_link",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="second_product_link",
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name="product",
            name="second_product_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="second_product_previous_price",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="second_product_text",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="third_product_current_price",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="third_product_description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="third_product_image_link",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="third_product_link",
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name="product",
            name="third_product_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="third_product_previous_price",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="third_product_text",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
